"""
Team bootstrap CLI for consuming shared-services platform outputs.

Generates backend.hcl for the team's own Terraform state and writes the
required CI variables and secrets to the team's GitHub repository. Reads
platform values from AWS SSM Parameter Store — no shared-services clone needed.

Usage:
  uv run team-setup/main.py run --team-slug team-payments
  uv run team-setup/main.py init --team-slug team-payments --output-dir ./terraform
  uv run team-setup/main.py show-outputs
"""

import json
import re
import subprocess
from pathlib import Path
from typing import Optional

import boto3
import typer
from lib.github import get_github_repo
from botocore.exceptions import ClientError, NoCredentialsError
from github import GithubException
from rich import print
from rich.console import Console
from rich.table import Table

app = typer.Typer(
    name="team-setup",
    help="Bootstrap a team repository to consume shared-services platform outputs.",
    no_args_is_help=True,
)
console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_ssm_outputs(namespace: str, region: str) -> dict[str, str]:
    """Read all shared-services parameters from SSM under the given namespace."""
    ssm = boto3.client("ssm", region_name=region)
    path = f"/shared-services/{namespace}/"
    params: dict[str, str] = {}
    try:
        paginator = ssm.get_paginator("get_parameters_by_path")
        for page in paginator.paginate(Path=path, Recursive=True):
            for p in page["Parameters"]:
                relative_key = p["Name"].removeprefix(path)
                params[relative_key] = p["Value"]
    except NoCredentialsError:
        print("[red]Error: No AWS credentials found. Configure your AWS profile or environment.[/red]")
        raise typer.Exit(1)
    except ClientError as e:
        print(f"[red]AWS error reading SSM: {e}[/red]")
        raise typer.Exit(1)
    return params


def _git_remote_repo() -> Optional[str]:
    """Parse 'owner/repo' from git remote origin URL."""
    result = subprocess.run(
        "git remote get-url origin",
        shell=True,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    url = result.stdout.strip()
    # SSH:   git@github.com:owner/repo.git
    # HTTPS: https://github.com/owner/repo.git
    match = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", url)
    return match.group(1) if match else None


def _write_backend_hcl(
    output_dir: Path,
    bucket: str,
    github_org: str,
    github_repo: str,
    team_guid: str,
    region: str,
) -> Path:
    """Write backend.hcl with the team's scoped state key."""
    path = output_dir / "backend.hcl"
    path.write_text(
        f'bucket       = "{bucket}"\n'
        f'key          = "teams/{github_org}/{github_repo}/{team_guid}/terraform.tfstate"\n'
        f'region       = "{region}"\n'
        f"use_lockfile = true\n"
        f"encrypt      = true\n"
    )
    return path


def _write_auto_tfvars(output_dir: Path, outputs: dict[str, str]) -> Path:
    """Write shared-services.auto.tfvars with resolved platform outputs."""
    path = output_dir / "shared-services.auto.tfvars"
    lines: list[str] = [
        "# Generated by team-setup — do not edit manually.\n",
        "# Re-run: uv run team-setup/main.py init ... to refresh.\n\n",
    ]

    ecr_push_role = outputs.get("dev/ecr-push-role-arn", "")
    if ecr_push_role:
        lines.append(f'ecr_push_role_arn = "{ecr_push_role}"\n')

    ecr_urls = {
        key.removeprefix("dev/ecr/").replace("--", "/"): val
        for key, val in outputs.items()
        if key.startswith("dev/ecr/")
    }
    if ecr_urls:
        lines.append("\necr_repository_urls = {\n")
        for name, url in sorted(ecr_urls.items()):
            lines.append(f'  "{name}" = "{url}"\n')
        lines.append("}\n")

    path.write_text("".join(lines))
    return path


def _resolve_repo(repo: Optional[str]) -> str:
    """Return the GitHub 'owner/repo' string, auto-detecting from git remote if not given."""
    detected = repo or _git_remote_repo()
    if not detected:
        print("[red]Error: Could not detect GitHub repo from git remote. Pass --repo owner/repo.[/red]")
        raise typer.Exit(1)
    return detected


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@app.command("check")
def check():
    """Verify prerequisites: AWS credentials and Terraform version."""
    table = Table(show_header=True, header_style="bold")
    table.add_column("Check")
    table.add_column("Status")
    table.add_column("Detail")

    # AWS credentials
    try:
        identity = boto3.client("sts").get_caller_identity()
        table.add_row("AWS credentials", "[green]✓ ok[/green]", identity.get("Arn", "ok"))
    except (ClientError, NoCredentialsError) as e:
        table.add_row("AWS credentials", "[red]✗ fail[/red]", str(e))

    # Terraform ≥ 1.10
    tf = subprocess.run("terraform version -json", shell=True, capture_output=True, text=True)
    if tf.returncode == 0:
        try:
            version = json.loads(tf.stdout)["terraform_version"]
            parts = [int(x) for x in version.split(".")[:2]]
            ok = parts >= [1, 10]
            status = "[green]✓ ok[/green]" if ok else "[yellow]⚠ outdated[/yellow]"
            table.add_row("Terraform ≥ 1.10", status, version)
        except (KeyError, ValueError, json.JSONDecodeError):
            table.add_row("Terraform ≥ 1.10", "[red]✗ fail[/red]", "version parse error")
    else:
        table.add_row("Terraform ≥ 1.10", "[red]✗ fail[/red]", "not found")

    console.print(table)


@app.command("show-outputs")
def show_outputs(
    namespace: str = typer.Option(..., envvar="SSM_NAMESPACE", help="Platform SSM namespace GUID"),
    region: str = typer.Option("ap-east-1", envvar="AWS_REGION", help="AWS region"),
):
    """Display all shared-services outputs published to SSM."""
    print(f"Reading SSM namespace [bold]{namespace}[/bold] in [bold]{region}[/bold]...")
    outputs = _get_ssm_outputs(namespace, region)

    if not outputs:
        print("[yellow]No parameters found. Has shared-services apply-dev run yet?[/yellow]")
        raise typer.Exit(1)

    table = Table(show_header=True, header_style="bold")
    table.add_column("SSM key (relative)")
    table.add_column("Value")
    for key in sorted(outputs):
        table.add_row(key, outputs[key])
    console.print(table)


@app.command("init")
def init(
    namespace: str = typer.Option(..., envvar="SSM_NAMESPACE", help="Platform SSM namespace GUID"),
    team_slug: str = typer.Option(..., "--team-slug", help="Team slug matching the shared-services IAM team file (e.g. team-payments)"),
    state_bucket: str = typer.Option(..., envvar="TF_STATE_BUCKET", help="Shared-services S3 state bucket name"),
    output_dir: Path = typer.Option(Path("."), "--output-dir", help="Directory to write generated files (default: current directory)"),
    generate_tfvars: bool = typer.Option(False, "--generate-tfvars", help="Also write shared-services.auto.tfvars with resolved platform values"),
    region: str = typer.Option("ap-east-1", envvar="AWS_REGION", help="AWS region"),
    repo: Optional[str] = typer.Option(None, "--repo", help="GitHub 'owner/repo' (auto-detected from git remote if omitted)"),
):
    """Generate backend.hcl for the team's Terraform state backend."""
    print(f"Reading SSM namespace [bold]{namespace}[/bold]...")
    outputs = _get_ssm_outputs(namespace, region)

    team_guid = outputs.get(f"iam/team-state-guid/{team_slug}", "")
    if not team_guid:
        print(f"[red]Error: No GUID found for '{team_slug}'. Has apply-iam run in shared-services?[/red]")
        raise typer.Exit(1)

    target_repo = _resolve_repo(repo)
    github_org, github_repo_name = target_repo.split("/", 1)
    output_dir.mkdir(parents=True, exist_ok=True)

    hcl_path = _write_backend_hcl(output_dir, state_bucket, github_org, github_repo_name, team_guid, region)
    print(f"✅ [green]Written:[/green] {hcl_path}")
    print(f"   key = teams/{github_org}/{github_repo_name}/[bold]{team_guid}[/bold]/terraform.tfstate")

    if generate_tfvars:
        tfvars_path = _write_auto_tfvars(output_dir, outputs)
        print(f"✅ [green]Written:[/green] {tfvars_path}")

    print("\nNext step: [bold]terraform init -backend-config=backend.hcl[/bold]")


@app.command("configure-github")
def configure_github(
    namespace: str = typer.Option(..., envvar="SSM_NAMESPACE", help="Platform SSM namespace GUID"),
    team_slug: str = typer.Option(..., "--team-slug", help="Team slug matching the shared-services IAM team file"),
    state_bucket: str = typer.Option(..., envvar="TF_STATE_BUCKET", help="Shared-services S3 state bucket name"),
    region: str = typer.Option("ap-east-1", envvar="AWS_REGION", help="AWS region"),
    repo: Optional[str] = typer.Option(None, "--repo", help="GitHub 'owner/repo' (auto-detected from git remote if omitted)"),
):
    """Write CI variables and secrets to the team's GitHub repository."""
    target_repo = _resolve_repo(repo)

    print(f"Reading SSM namespace [bold]{namespace}[/bold]...")
    outputs = _get_ssm_outputs(namespace, region)

    deployer_role_arn = outputs.get(f"iam/deployer-role-arn/{team_slug}", "")
    ecr_push_role_arn = outputs.get("dev/ecr-push-role-arn", "")
    team_guid = outputs.get(f"iam/team-state-guid/{team_slug}", "")

    if not deployer_role_arn:
        print(f"[red]Error: No deployer role found for '{team_slug}'. Has apply-iam run in shared-services?[/red]")
        raise typer.Exit(1)

    try:
        gh_repo = get_github_repo(target_repo)

        for name, value in [
            ("TF_STATE_BUCKET", state_bucket),
            ("SSM_NAMESPACE", namespace),
            ("AWS_REGION", region),
            ("TEAM_STATE_GUID", team_guid),
        ]:
            gh_repo.create_variable(name, value)
            print(f"✅ [green]Variable set:[/green] {name} = {value}")

        for name, value in [
            ("DEPLOYER_ROLE_ARN", deployer_role_arn),
            ("ECR_PUSH_ROLE_ARN", ecr_push_role_arn),
        ]:
            gh_repo.create_secret(name, value)
            print(f"🔒 [green]Secret set:[/green] {name}")

        print(f"\n✅ [bold green]GitHub configured for {target_repo}[/bold green]")

    except GithubException as e:
        print(f"[red]GitHub API error: {e}[/red]")
        raise typer.Exit(1)


@app.command("status")
def status(
    output_dir: Path = typer.Option(Path("."), "--output-dir"),
    namespace: Optional[str] = typer.Option(None, envvar="SSM_NAMESPACE"),
    region: str = typer.Option("ap-east-1", envvar="AWS_REGION"),
):
    """Show current setup state: generated files and SSM reachability."""
    table = Table(show_header=True, header_style="bold")
    table.add_column("Item")
    table.add_column("Status")
    table.add_column("Detail")

    for filename in ("backend.hcl", "shared-services.auto.tfvars"):
        p = output_dir / filename
        if p.exists():
            table.add_row(filename, "[green]✓ exists[/green]", str(p))
        else:
            table.add_row(filename, "[yellow]missing[/yellow]", "run: team-setup init")

    if namespace:
        try:
            outputs = _get_ssm_outputs(namespace, region)
            table.add_row("SSM namespace", "[green]✓ reachable[/green]", f"{len(outputs)} parameters found")
        except SystemExit:
            table.add_row("SSM namespace", "[red]✗ unreachable[/red]", f"namespace: {namespace}")
    else:
        table.add_row("SSM namespace", "[yellow]unknown[/yellow]", "set SSM_NAMESPACE env var")

    console.print(table)


@app.command("run")
def run(
    namespace: str = typer.Option(..., envvar="SSM_NAMESPACE", help="Platform SSM namespace GUID"),
    team_slug: str = typer.Option(..., "--team-slug", help="Team slug matching the shared-services IAM team file"),
    state_bucket: str = typer.Option(..., envvar="TF_STATE_BUCKET", help="Shared-services S3 state bucket name"),
    output_dir: Path = typer.Option(Path("."), "--output-dir"),
    region: str = typer.Option("ap-east-1", envvar="AWS_REGION"),
    repo: Optional[str] = typer.Option(None, "--repo"),
):
    """Run the full bootstrap sequence: init then configure-github."""
    console.rule("[bold]Team setup[/bold]")

    init(
        namespace=namespace,
        team_slug=team_slug,
        state_bucket=state_bucket,
        output_dir=output_dir,
        generate_tfvars=False,
        region=region,
        repo=repo,
    )

    print()
    if typer.confirm("Configure GitHub repository now?", default=True):
        configure_github(
            namespace=namespace,
            team_slug=team_slug,
            state_bucket=state_bucket,
            region=region,
            repo=repo,
        )

    console.rule("[bold green]Done[/bold green]")


if __name__ == "__main__":
    app()
